### ISSUE TITLE
How to use with coffeescript?

### ISSUE THREAD

**Issue by wmertens** [ColCh/jest-webpack#2] opened 2015-03-29 11:39 UTC
This seems to ignore the webpack config, so it doesn't know about custom loaders like coffeescript and less, or am I mistaken?

**Comment by ColCh** [comment] 2015-04-05 09:32
You're right... Any thoughts on using webpack config? I think that adding new option to _package.json_ (which points to config) will help with this a lot

**Comment by wmertens** [comment] 2015-04-05 21:49
now that I think of it, wouldn't it be better to make jest a sort of loader for webpack? You'd have to `require()` the tests which may be a little tedious, but it could then run the test automatically if the test changes, and vice versa. Or even make the tests a second entry point, and they would point to their dependencies properly...

**Comment by wmertens** [comment] 2015-04-05 21:51
@ColCh and if you could somehow load jest instead of running the binary, the tests could go a lot faster because it would have the full setup ready to run... That would be seriously awesome...

**Comment by ColCh** [comment] 2015-04-06 10:07
This is exactly webpack's _loader_ behaviour. This script works like _karma-webpack_. Unfortunately I can't keep Jest loaded because webpack is used here as preprocessor (which is wrong by design)

**Comment by ColCh** [comment] 2015-04-06 11:01
As 0.2.0 it has possibility to load config for webpack. It's specified with **jest-webpack-config** package.json key.  See test fixture for more info.

**Comment by ColCh** [comment] 2015-04-07 14:33
Closing since resolved

**Closed as completed by ColCh** 2015-04-07 14:33 UTC

**Comment by wmertens** [comment] 2015-04-08 08:12
Cool thanks! I also realized that a jest-loader wouldn't work with webpack because it overrides `require` to provide mocks. Webpack would not be able to know which ones are mocked.

...unless the jest-loader keeps track of mocks of course... hmmm.

**Comment by ColCh** [comment] 2015-04-09 19:32
Yes... That's another sort of problem. I think that should be implemented within _jest-loader_ functionality.
